language: java

sudo: false

jdk:
  - openjdk8

script: mvn clean package

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"
    - NUM_THREADS=2
    - NODE_VERSION="8.11.3"

before_install:
  - nvm install $NODE_VERSION
  - npm install -g @angular/cli

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/969b5598af30afd3e0a2
    on_success: always
    on_failure: always
    on_start: never

addons:
  sonarcloud:
    organization: "pdxfinder"
    token:
      secure: "4227c79f48a56b863a5e889f6ac7f591cf9d60d9"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
